import * as stylex from "@stylexjs/stylex";
import type { Attribute } from "foldkit/html";
import type { html } from "foldkit/html";

import { colors, shadows } from "./theme.stylex.ts";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

type StyleInput =
  | stylex.StyleXStyles
  | stylex.Theme<typeof colors>
  | stylex.Theme<typeof shadows>
  | false
  | null
  | undefined;
type HtmlFactory<Message> = ReturnType<typeof html<Message>>;

const toStyleRecord = (
  style: Readonly<{ readonly [key: string]: string | number }> | undefined,
): Record<string, string> => {
  const record: Record<string, string> = {};
  if (!style) return record;
  for (const [key, value] of Object.entries(style)) record[key] = String(value);
  return record;
};

export const sx = <Message>(
  h: HtmlFactory<Message>,
  ...styles: ReadonlyArray<StyleInput>
): ReadonlyArray<Attribute<Message>> => {
  const props = stylex.props(...styles);
  const attributes: Array<Attribute<Message>> = [];
  if (props.className) attributes.push(h.Class(props.className));
  if (props.style) attributes.push(h.Style(toStyleRecord(props.style)));
  return attributes;
};

export const appStyles = stylex.create({
  root: {
    minHeight: "100vh",
    backgroundColor: colors.bg,
    color: colors.text,
    fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
    WebkitFontSmoothing: "antialiased",
    colorScheme: "light",
  },
  rootDark: { colorScheme: "dark" },
  shell: {
    height: { default: "100vh", "@media (max-width: 760px)": "auto" },
    minHeight: "100vh",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    minHeight: 48,
    padding: { default: "0 14px", "@media (max-width: 680px)": "8px 10px" },
    flexWrap: { default: "nowrap", "@media (max-width: 680px)": "wrap" },
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.line,
    backgroundColor: colors.panel,
  },
  brand: { display: "flex", alignItems: "center", gap: 9 },
  brandCopy: { display: "flex", flexDirection: "column", minWidth: 0 },
  brandMark: {
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: "currentColor",
    color: colors.accent,
  },
  brandName: {
    margin: 0,
    fontSize: 15,
    lineHeight: "18px",
    fontWeight: 650,
    letterSpacing: -0.1,
  },
  brandSub: {
    margin: 0,
    color: colors.textSoft,
    fontSize: 10,
    lineHeight: "13px",
    fontVariantNumeric: "tabular-nums",
  },
  stateRun: { color: colors.run },
  stateAcquire: { color: colors.acquire },
  stateHalt: { color: colors.halt },
  stateFault: { color: colors.danger },
  stateIdle: { color: colors.textSoft },
  spacer: { flex: 1, minWidth: 0 },
  cluster: { display: "flex", alignItems: "center", gap: 8 },
  miniStatus: {
    display: { default: "inline-flex", "@media (max-width: 680px)": "none" },
    color: colors.textSoft,
    fontSize: 11,
    fontVariantNumeric: "tabular-nums",
  },
  body: {
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr) auto",
    gap: 10,
    padding: { default: 12, "@media (max-width: 680px)": 8 },
  },
  screen: {
    minHeight: { default: 520, "@media (max-width: 760px)": 600 },
    overflow: "hidden",
    display: "grid",
    gridAutoRows: "minmax(92px, 1fr)",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    backgroundColor: colors.panel,
  },
  plotEmpty: {
    display: "grid",
    placeItems: "center",
    minHeight: 360,
    color: colors.textSoft,
    fontSize: 12,
  },
  signalRow: {
    minHeight: 0,
    display: "block",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.line,
    ":last-child": { borderBottomWidth: 0 },
  },
  plotViewport: {
    width: "100%",
    height: "100%",
    minWidth: 0,
    minHeight: 0,
    position: "relative",
    backgroundColor: colors.screen,
  },
  plotLegend: {
    position: "absolute",
    top: 7,
    left: 8,
    zIndex: 2,
    maxWidth: "calc(100% - 84px)",
    overflow: "hidden",
    padding: "2px 6px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    borderRadius: 4,
    backgroundColor: colors.legendBg,
    fontSize: 10,
    lineHeight: "14px",
    fontWeight: 650,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    pointerEvents: "none",
  },
  plotCanvas: { display: "block", width: "100%", height: "100%" },
  dock: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    padding: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.panel,
  },
  dockGroup: { display: "flex", alignItems: "center", gap: 7, flexWrap: "wrap" },
  dockDivider: {
    width: 1,
    minHeight: 24,
    alignSelf: "stretch",
    backgroundColor: colors.line,
  },
  spinner: {
    width: 12,
    height: 12,
    flexShrink: 0,
    boxSizing: "border-box",
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: colors.accentBorder,
    borderTopColor: colors.accentStrong,
    borderRadius: 999,
    animationName: spin,
    animationDuration: "700ms",
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
  controlShape: {
    boxSizing: "border-box",
    height: 32,
    minHeight: 32,
    borderRadius: 6,
    whiteSpace: "nowrap",
  },
  // Device-derived labels vary in length; clip them rather than let a long
  // label spill over the neighbouring control.
  controlLabel: { minWidth: 0, overflow: "hidden", textOverflow: "ellipsis" },
  controlRunStop: { width: 64, flex: "0 0 64px" },
  controlTriggerAction: { width: 74, flex: "0 0 74px" },
  controlTimebase: { width: 72, flex: "0 0 72px" },
  controlTrigger: { width: 142, flex: "0 0 142px" },
  controlChannels: { width: 82, flex: "0 0 82px" },
  controlRt: { width: 88, flex: "0 0 88px" },
  controlSnapshots: { width: 92, flex: "0 0 92px" },
  controlSave: { width: 122, flex: "0 0 122px" },
  activityButton: { position: "relative", minWidth: 76 },
  activityBadge: {
    position: "absolute",
    top: -6,
    right: -6,
    minWidth: 16,
    height: 16,
    boxSizing: "border-box",
    display: "grid",
    placeItems: "center",
    padding: "0 4px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.panel,
    borderRadius: 999,
    backgroundColor: colors.danger,
    color: colors.panel,
    fontSize: 9,
    fontWeight: 700,
    lineHeight: "14px",
  },
  activityBadgeWarning: { backgroundColor: colors.acquire },
  btn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "0 11px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.lineStrong,
    backgroundColor: colors.panel,
    color: colors.text,
    font: "inherit",
    fontSize: 12,
    fontWeight: 550,
    cursor: "pointer",
    transitionProperty: "background-color, border-color, color, transform",
    transitionDuration: "120ms",
    ":hover": { backgroundColor: colors.panelRaised },
    ":active": { transform: "translateY(1px)" },
    ":disabled": { opacity: 0.42, cursor: "not-allowed", transform: "none" },
    ":focus-visible": {
      outlineWidth: 2,
      outlineStyle: "solid",
      outlineColor: colors.accent,
      outlineOffset: 2,
    },
  },
  btnSmall: { padding: "0 9px", fontSize: 11 },
  linkBtn: { textDecoration: "none" },
  viewerHint: {
    margin: 0,
    color: colors.textSoft,
    fontSize: 11,
    lineHeight: "16px",
    textAlign: "center",
  },
  btnPrimary: {
    borderColor: colors.text,
    backgroundColor: colors.text,
    color: colors.panel,
    ":hover": { backgroundColor: colors.textRaised },
  },
  btnRun: {
    borderColor: colors.runBorder,
    backgroundColor: colors.runSoft,
    color: colors.run,
    ":hover": { backgroundColor: colors.runSoftRaised },
  },
  btnStop: {
    borderColor: colors.dangerBorder,
    backgroundColor: colors.dangerSoft,
    color: colors.danger,
    ":hover": { backgroundColor: colors.dangerSoftRaised },
  },
  btnActive: {
    borderColor: colors.accentBorder,
    color: colors.accentStrong,
    backgroundColor: colors.accentSoft,
  },
  field: { display: "flex", flexDirection: "column", gap: 5, minWidth: 0 },
  fieldLabel: { color: colors.textMuted, fontSize: 11, lineHeight: "14px", fontWeight: 600 },
  input: {
    width: "100%",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.lineStrong,
    backgroundColor: colors.panel,
    color: colors.text,
    padding: "0 9px",
    font: "inherit",
    fontSize: 12,
    fontVariantNumeric: "tabular-nums",
    "::placeholder": { color: colors.textSoft },
    ":focus-visible": {
      borderColor: colors.accent,
      outlineWidth: 2,
      outlineStyle: "solid",
      outlineColor: colors.focusRing,
      outlineOffset: 1,
    },
  },
  select: {
    minWidth: 0,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.lineStrong,
    backgroundColor: colors.panel,
    color: colors.text,
    padding: "0 9px",
    font: "inherit",
    fontSize: 12,
    cursor: "pointer",
    ":focus-visible": {
      borderColor: colors.accent,
      outlineWidth: 2,
      outlineStyle: "solid",
      outlineColor: colors.focusRing,
      outlineOffset: 1,
    },
  },
  portSelector: {
    width: { default: 280, "@media (max-width: 680px)": 210 },
    maxWidth: "45vw",
    display: "block",
    overflow: "hidden",
    textAlign: "left",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  popoverAnchor: { position: "relative", display: "inline-flex" },
  portsPopover: {
    position: "absolute",
    top: "calc(100% + 8px)",
    right: 0,
    zIndex: 60,
    width: { default: 620, "@media (max-width: 680px)": "calc(100vw - 20px)" },
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.lineStrong,
    backgroundColor: colors.panel,
    boxShadow: shadows.popover,
  },
  portsTableWrap: {
    maxHeight: 300,
    overflow: "auto",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    borderRadius: 6,
  },
  portsTable: { fontSize: 11 },
  portsEmpty: { padding: 24, color: colors.textSoft, textAlign: "center" },
  portRow: {
    position: "relative",
    cursor: "pointer",
    ":focus-within": {
      outlineWidth: 2,
      outlineStyle: "solid",
      outlineColor: colors.accent,
      outlineOffset: -2,
    },
  },
  portRowSelected: { backgroundColor: colors.accentSoft },
  portChoice: {
    maxWidth: 260,
    overflow: "hidden",
    borderWidth: 0,
    padding: 0,
    backgroundColor: "transparent",
    color: colors.text,
    font: "inherit",
    fontWeight: 600,
    textAlign: "left",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    cursor: "pointer",
    "::after": { content: "", position: "absolute", inset: 0 },
    ":disabled": { opacity: 0.45, cursor: "not-allowed" },
    ":focus-visible": {
      outlineWidth: 2,
      outlineStyle: "solid",
      outlineColor: colors.accent,
      outlineOffset: 2,
    },
  },
  portChoiceSelected: { color: colors.accentStrong },
  popoverPanel: {
    position: "absolute",
    bottom: "calc(100% + 10px)",
    left: 0,
    zIndex: 60,
    width: 284,
    display: "flex",
    flexDirection: "column",
    gap: 11,
    padding: 13,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.lineStrong,
    backgroundColor: colors.panel,
    boxShadow: shadows.popover,
  },
  popoverWide: { width: { default: 380, "@media (max-width: 520px)": "calc(100vw - 28px)" } },
  saveSnapshotPopover: { right: 0, left: "auto" },
  activityPopover: {
    top: "calc(100% + 8px)",
    bottom: "auto",
    right: 0,
    left: "auto",
    width: 420,
    maxWidth: "calc(100vw - 28px)",
  },
  popoverHeader: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 8,
  },
  cardTitle: { margin: 0, color: colors.text, fontSize: 12, lineHeight: "15px", fontWeight: 650 },
  cardMeta: {
    color: colors.textSoft,
    fontSize: 10,
    lineHeight: "14px",
    fontVariantNumeric: "tabular-nums",
  },
  popoverRow: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 10 },
  popoverList: {
    maxHeight: 340,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    paddingRight: 2,
  },
  activityHint: { margin: "3px 0 0", color: colors.textSoft, fontSize: 10, lineHeight: "14px" },
  activityList: {
    maxHeight: 300,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 7,
  },
  activityEntry: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
    padding: 9,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    borderRadius: 6,
    backgroundColor: colors.panelMuted,
  },
  activityEntryHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  activityLevel: {
    fontSize: 9,
    fontWeight: 700,
    lineHeight: "12px",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  activityLevelWarning: { color: colors.acquire },
  activityLevelError: { color: colors.danger },
  activityTime: { color: colors.textSoft, fontSize: 9, lineHeight: "12px" },
  activityMessage: {
    margin: 0,
    color: colors.text,
    fontSize: 11,
    lineHeight: "16px",
    overflowWrap: "anywhere",
  },
  activityEmpty: {
    padding: "18px 10px",
    color: colors.textSoft,
    fontSize: 11,
    textAlign: "center",
  },
  mappingRow: {
    display: "grid",
    gridTemplateColumns: "92px minmax(0, 1fr)",
    alignItems: "center",
    gap: 9,
  },
  popoverActions: { display: "flex", justifyContent: "flex-end", gap: 7 },
  mappingIndex: {
    overflow: "hidden",
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: 550,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  dialog: {
    position: "fixed",
    inset: { default: 28, "@media (max-width: 680px)": 10 },
    zIndex: 60,
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    gap: 14,
    padding: 18,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.lineStrong,
    backgroundColor: colors.panel,
    boxShadow: shadows.dialog,
  },
  rtGrid: {
    minHeight: 0,
    overflowY: "auto",
    alignContent: "start",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: 14,
    paddingRight: 2,
  },
  dialogHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
  },
  dialogTitle: {
    margin: 0,
    fontSize: 18,
    lineHeight: "24px",
    fontWeight: 680,
    letterSpacing: -0.25,
  },
  helperText: { margin: 0, color: colors.textSoft, fontSize: 11, lineHeight: "16px" },
  settingsGrid: {
    minHeight: 0,
    overflowY: "auto",
    alignContent: "start",
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 760px)": "1fr",
    },
    gap: 14,
    paddingRight: 2,
  },
  settingsSection: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: 14,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.panelMuted,
  },
  settingsSectionTitle: {
    margin: 0,
    color: colors.text,
    fontSize: 13,
    lineHeight: "18px",
    fontWeight: 650,
  },
  settingsFields: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 10,
  },
  checkboxField: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: "16px",
  },
  restartNote: {
    margin: 0,
    padding: "8px 10px",
    borderRadius: 6,
    backgroundColor: colors.acquireSoft,
    color: colors.acquire,
    fontSize: 11,
    lineHeight: "16px",
  },
  tableWrap: {
    minHeight: 0,
    overflow: "auto",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    borderRadius: 8,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 12,
    fontVariantNumeric: "tabular-nums",
  },
  tableHead: {
    position: "sticky",
    top: 0,
    padding: "9px 11px",
    backgroundColor: colors.panelRaised,
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: 650,
    textAlign: "left",
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  tableRow: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.line,
    ":hover": { backgroundColor: colors.panelMuted },
  },
  tableCell: { padding: "10px 11px", color: colors.textMuted, whiteSpace: "nowrap" },
  tableName: { color: colors.text, fontWeight: 600 },
  tableActions: { textAlign: "right" },
  tableActionsCluster: { justifyContent: "flex-end" },
  iconButton: { width: 32, minWidth: 32, padding: 0, fontSize: 18, lineHeight: 1 },
  starred: { color: colors.acquire, borderColor: colors.acquireBorder },
  deleteAnchor: { position: "relative", display: "inline-flex" },
  deletePopover: {
    position: "absolute",
    top: "calc(100% + 6px)",
    right: 0,
    zIndex: 20,
    width: 190,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 11,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.lineStrong,
    borderRadius: 7,
    backgroundColor: colors.panelRaised,
    boxShadow: shadows.popover,
  },
  deletePrompt: {
    margin: 0,
    overflow: "hidden",
    color: colors.text,
    fontSize: 11,
    lineHeight: "16px",
    textOverflow: "ellipsis",
    whiteSpace: "normal",
  },
  tableEmpty: { padding: 32, color: colors.textSoft, textAlign: "center" },
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 40,
    borderWidth: 0,
    padding: 0,
    cursor: "default",
    backgroundColor: colors.overlay,
  },
  errorBanner: {
    padding: "7px 11px",
    borderRadius: 6,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.dangerBorder,
    backgroundColor: colors.dangerSoft,
    color: colors.danger,
    fontSize: 12,
    lineHeight: "16px",
  },
  localErrorToast: {
    position: "fixed",
    right: 14,
    bottom: 62,
    zIndex: 70,
    maxWidth: "min(440px, calc(100vw - 28px))",
    padding: "8px 11px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.dangerBorder,
    borderRadius: 6,
    backgroundColor: colors.dangerSoft,
    color: colors.danger,
    boxShadow: shadows.popover,
    fontSize: 11,
    lineHeight: "16px",
  },
});
